export { Header } from './components/Header/Header'
export { Logo } from './components/Header/Logo'
export { Cv } from './components/Header/Cv'
export { Navbar } from './components/Header/Navbar'
export { Menuresponsive } from './components/Header/Menu-responsive'
export { Main } from './components/Main/Main'
export { Hero } from './components/Hero/Hero'
export { Titulos } from './components/Hero/Hero-textos'
export { Redeshero } from './components/Hero/Redes-hero'
export { Imghero } from './components/Hero/Img-hero'
export { FaInstagram } from 'react-icons/fa'
export { FaBehance } from 'react-icons/fa';
export { FaFacebook } from 'react-icons/fa';
export { FaGithub} from 'react-icons/fa';
export { FaPhone } from 'react-icons/fa'
export { Sobremi } from './components/Sobre-mi/Sobremi'
export { Textosobremi } from './components/Sobre-mi/Texto-sobremi'
export { Imgsobremi } from './components/Sobre-mi/Img-sobremi'
export { Misservicios } from './components/Mis-servicios/Mis-servicios'
export { CardBlack } from './components/Mis-servicios/Card-Black'
export { Cardbranding } from './components/Mis-servicios/Card-branding'
export { Miportfolio } from './components/Mi-portfolio/Miportfolio'
export { Portfolio} from './components/Mi-portfolio/Portfolio'
export { Slide } from './components/Mi-portfolio/Slide'
export { Contacto } from './components/Contacto/Contacto'
export { Formulario } from './components/Contacto/Formulario'
export { TextoContacto } from './components/Contacto/Texto-contacto'
export { Footer } from './components/Footer/Footer'
